package main

import (
	"fmt"

	"github.com/weslygio/Tubes3_13520071/src/pkg/dna"
)

func main() {
	sampleSeq := "AATTTCGATCGCCCTATTAGAGCTCCCTCTGGGATATATGCCCTAGCTGGCTAGCATATATGCCGCGCGCGTATAGCTAGTCGTGTGATCAGCATAAACGCGCTGTAGCTGATCGGATTCGATATAGCTCTAATCATATATATGAGAGGAGGCCCCTTTAAATCCCGGGGTATATAGCCGCGCGTATATTTTAAGAAAAGCGCCGCCGGCGCGCTAGCTAGTCCTCAGTCTAAATATTACTGCGCTAGCTAG"
	virusSeq := "TATGATCATACGCTAGCTAGCTATATCGATCGATCGATCGATTTAGTCCGCGTGAG"

	if !dna.IsDNAValid(sampleSeq) {
		fmt.Println("sample sequence invalid")
		return
	}

	if !dna.IsDNAValid(virusSeq) {
		fmt.Println("virus sequence invalid")
		return
	}

	fmt.Println(dna.IsDNAMatched(sampleSeq, virusSeq))
}
